// mytweets-react/src/LikeBtn/LikeBtn.jsx
import React, { Component } from 'react'
import PropTypes from 'prop-types'

import './LikeBtn.css'

class LikeBtn extends Component {

  state = {
    likes: Number(this.props.likes),
    isLiked: false
  }

  handleClick = () => {
    this.setState((state) => ({
      likes: state.isLiked ? state.likes - 1 : state.likes + 1,
      isLiked: !state.isLiked
    }))
  }

  render() {
    const { isLiked, likes } = this.state
    return (
      <div className={isLiked ? "like-btn liked" : "like-btn"} onClick={this.handleClick}>
        <i className="material-icons">favorite</i>
        <span>{likes}</span>
      </div>
    )
  }
}

LikeBtn.propTypes = {
  likes: PropTypes.string,
}

export default LikeBtn

// mytweets-angular/src/app/like-btn/like-btn.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'app-like-btn',
  templateUrl: './like-btn.component.html',
  styleUrls: ['./like-btn.component.css']
})
export class LikeBtnComponent implements OnInit {

  @Input() data: any;

  constructor() { }

  ngOnInit() {
  }

  public onClick() {
    this.data.isLiked ? this.data.likes-- : this.data.likes++;
    this.data.isLiked = !this.data.isLiked;
  }

}

<div class="like-btn" [ngClass]="{'liked': data.isLiked}">
  <div>{{data.likes}}</div>
  <i class="material-icons" (click)="onClick()">favorite</i>
</div>
